### ISSUE TITLE
Unreasonable results when dealing with crystal structures

### ISSUE THREAD

**Issue by OliverYL** [MorrowChem/julia_rings#1]
Dear developers,

I used julia_rings to get ring statistics and met some problems as follows. I did tests on Si, SiO2, and Ga2O3 systems and the issues happen when dealing with crystal systems.

- For crystal silicon (diamond structure), the ring statistics are wrong when using conventional unit cell and 2 $\times$ 2 $\times$ 2 supercell, while this problem disappear when using larger supercells.
- For alpha-silica (non-orthogonal cell), the ring statistics are wrong when using small supercells and no rings can be got when using larger supercells. I also tried equivlent orthogonal cell generated by atomsk and get similar results.
- For beta-Ga2O3, the ring statistics become correct when using larger supercells. However, 2-membered ring appears and the statistics seems not reasonable when using equivlent orthogonal cell generated by atomsk. Of course, this problem might result from the orthogonal cell generation, and I am still checking it.

The above-mentioned structures are attached, the structures, ring statistics, and calculation python codes are in respective directories.

Do you have any ideas about the problems and could you help to check? 

Thank you~

Lei

[issue-0921.zip](https://github.com/MorrowChem/julia_rings/files/12679773/issue-0921.zip)

**Comment by MorrowChem** [comment]
Hi Lei,

Thanks for raising this (and for the very organised examples 😊)- you're right that the rings are wrong for small cells. I've made a change to automatically make supercells if you give the code a structure that is too small to fit the 'maxlvl' in without having an infinite chain under PBCs. The example for diamond Si now gives the expected output:

Ring statistics:
Ring Size \|            Count 
----------\|------------------
        1 |             0.0
        2 |             0.0
        3 |             0.0
        4 |             0.0
        5 |             0.0
        6 |            16.0
        7 |             0.0
        8 |             0.0
        8 |             0.0
        
I've also fixed the printing bug that wasn't showing the larger ring sizes - when I run your script on your a-quartz SiO2, I now get the following result, which is correct (these ring sizes include the O atoms as nodes, so N=12,16 means N_Si=6,8 which matches the expected 1:5 ratio, I believe)
        
`python run_rings.py POSCAR-SiO2-orth --maxlvl 24` 
 or
 `python run_rings.py POSCAR-SiO2-unit --maxlvl 24`
       
 e.g. 
Ring statistics:
Ring Size \|            Count 
----------\|------------------
        1 |             0.0
        2 |             0.0
        3 |             0.0
        4 |             0.0
        5 |             0.0
        6 |             0.0
        7 |             0.0
        8 |             0.0
        9 |             0.0
       10 |             0.0
       11 |             0.0
       12 |             6.0
       13 |             0.0
       14 |             0.0
       15 |             0.0
       16 |            30.0
       17 |             0.0
       18 |             0.0

I've also checked the results for Ga2O3, and these also seem reasonable (not sure of the exact ratios, but I can definitely see 4, 6, and 8-rings in there)

Do let me know if there are any further problems, always happy to help

**Comment by OliverYL** [comment]
Hi Morrow,

Thank you for your reply and updating the code. 🫡

I did the test and I think the problem is solved. As for the Ga2O3 case, it should be 4, 6, and 8-rings there and I found the ratio is a little different with the results from RINGS code. I will check. 

Thank you for your help.

Lei
